# Generated by Django 5.1 on 2024-08-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
