# Generated by Django 5.1 on 2024-08-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0002_userdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(default='Abc', max_length=50),
        ),
    ]
